### ISSUE TITLE
price error

### ISSUE THREAD

**Issue by belikesayantan** [obli99/wle#3]
`integer_item_price = int(item_price.replace('₹\xa0', '').split('.')[0].replace(',', ''))`

the integer_item_price works only in amazon.in 
error in websites such as amazon.de 
error in amazon.fr coz currency after price value

**Comment by beebus** [comment]
@belikesayantan ,
Please refer to https://github.com/obli99/wle/pull/4
This pull request corrects this issue.
Let me know if you have any questions.

**Comment by belikesayantan** [comment]
@beebus ,
thanks a lot for the help
